apiVersion: v1
kind: Service
metadata:
  name: orders-api
  labels:
    app: orders-api
    app.kubernetes.io/part-of: orders
spec:
  type: ClusterIP
  selector:
    app: orders-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
